language: node_js
node_js:
  - "0.11"
install:
  - "npm install -g typescript"
script:
  - "tsc --version"
  - "tsc ./src/core/KeyActionBinder.ts -t es5 -noImplicitAny -module amd"
#script: gulp test --verbose --force